from __future__ import annotations

import os
import warnings
from collections.abc import Iterator
from dataclasses import dataclass
from uuid import uuid4

import oracledb
import pytest
from data_connector.oracle_vpd import OracleVPDClient, OracleVPDPoolConfig, create_proxy_pool

ADMIN_USER = os.getenv("AIAL_ORACLE_ADMIN_USER", "system")
ADMIN_PASSWORD = os.getenv("AIAL_ORACLE_ADMIN_PASSWORD", "oracle")
DSN = os.getenv("AIAL_ORACLE_DSN", "localhost:1521/FREEPDB1")
OWNER_USER = "AIAL_VPD_OWNER"
OWNER_PASSWORD = os.getenv("AIAL_ORACLE_OWNER_PASSWORD", "AialOwnerPwd123")
PROXY_USER = "AIAL_PROXY"
PROXY_PASSWORD = os.getenv("AIAL_ORACLE_PROXY_PASSWORD", "AialProxyPwd123")
SESSION_USER = "AIAL_APP_PRINCIPAL"
SESSION_PASSWORD = os.getenv("AIAL_ORACLE_SESSION_PASSWORD", "AialPrincipalPwd123")
CONTEXT_NAMESPACE = "AIAL_VPD_CTX"
TABLE_NAME = "AIAL_VPD_ROWS"
PACKAGE_NAME = "AIAL_VPD_CTX_PKG"
PREDICATE_FUNCTION = "AIAL_VPD_PREDICATE"
POLICY_NAME = "AIAL_VPD_POLICY"


def _oracle_tests_enabled() -> bool:
    return os.getenv("AIAL_RUN_ORACLE_VPD_TESTS") == "1"


pytestmark = [
    pytest.mark.requires_oracle,
    pytest.mark.security_gate,
    pytest.mark.skipif(not _oracle_tests_enabled(), reason="set AIAL_RUN_ORACLE_VPD_TESTS=1 to run Oracle VPD gate"),
]


@dataclass(frozen=True)
class OracleSmokeConfig:
    admin_user: str = ADMIN_USER
    admin_password: str = ADMIN_PASSWORD
    dsn: str = DSN


def _connect(user: str, password: str, dsn: str) -> oracledb.Connection:
    return oracledb.connect(user=user, password=password, dsn=dsn)


def _admin_execute(cursor: oracledb.Cursor, statement: str) -> None:
    cursor.execute(statement)


def _drop_user_if_exists(cursor: oracledb.Cursor, username: str) -> None:
    cursor.execute("select count(*) from dba_users where username = :username", username=username.upper())
    if cursor.fetchone()[0]:
        _admin_execute(cursor, f"drop user {username} cascade")


def _drop_context_if_exists(cursor: oracledb.Cursor, namespace: str) -> None:
    cursor.execute("select count(*) from dba_context where namespace = :namespace", namespace=namespace.upper())
    if cursor.fetchone()[0]:
        _admin_execute(cursor, f"drop context {namespace}")


def _cleanup_security_objects(connection: oracledb.Connection) -> None:
    with connection.cursor() as cursor:
        _drop_context_if_exists(cursor, CONTEXT_NAMESPACE)
        for username in (SESSION_USER, PROXY_USER, OWNER_USER):
            _drop_user_if_exists(cursor, username)
    connection.commit()


def _bootstrap_users(connection: oracledb.Connection) -> None:
    with connection.cursor() as cursor:
        _admin_execute(cursor, f"create user {OWNER_USER} identified by {OWNER_PASSWORD}")
        _admin_execute(cursor, f"grant create session, create table, create procedure to {OWNER_USER}")
        _admin_execute(cursor, f"alter user {OWNER_USER} quota unlimited on users")

        _admin_execute(cursor, f"create user {PROXY_USER} identified by {PROXY_PASSWORD}")
        _admin_execute(cursor, f"grant create session to {PROXY_USER}")

        _admin_execute(cursor, f"create user {SESSION_USER} identified by {SESSION_PASSWORD}")
        _admin_execute(cursor, f"grant create session to {SESSION_USER}")
        _admin_execute(cursor, f"alter user {SESSION_USER} grant connect through {PROXY_USER}")
    connection.commit()


def _bootstrap_owner_objects(config: OracleSmokeConfig) -> None:
    with _connect(OWNER_USER, OWNER_PASSWORD, config.dsn) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                f"""
                create table {TABLE_NAME} (
                    row_id number generated by default on null as identity primary key,
                    department_id varchar2(30) not null,
                    scope_value varchar2(100) not null
                )
                """
            )
            cursor.execute(f"insert into {TABLE_NAME} (department_id, scope_value) values ('sales', 'sales-only-row')")
            cursor.execute(
                f"insert into {TABLE_NAME} (department_id, scope_value) values ('finance', 'finance-only-row')"
            )
            cursor.execute(
                f"""
                create or replace package {PACKAGE_NAME} as
                    procedure set_scope(p_department_id varchar2, p_principal_id varchar2);
                    procedure clear_scope;
                end {PACKAGE_NAME};
                """
            )
            cursor.execute(
                f"""
                create or replace package body {PACKAGE_NAME} as
                    procedure set_scope(p_department_id varchar2, p_principal_id varchar2) as
                    begin
                        dbms_session.set_context('{CONTEXT_NAMESPACE}', 'DEPARTMENT_ID', p_department_id);
                        dbms_session.set_context('{CONTEXT_NAMESPACE}', 'PRINCIPAL_ID', p_principal_id);
                    end set_scope;

                    procedure clear_scope as
                    begin
                        dbms_session.clear_context('{CONTEXT_NAMESPACE}', null, 'DEPARTMENT_ID');
                        dbms_session.clear_context('{CONTEXT_NAMESPACE}', null, 'PRINCIPAL_ID');
                    end clear_scope;
                end {PACKAGE_NAME};
                """
            )
            cursor.execute(
                f"""
                create or replace function {PREDICATE_FUNCTION}(
                    schema_name varchar2,
                    object_name varchar2
                ) return varchar2 as
                    l_department varchar2(30);
                begin
                    l_department := sys_context('{CONTEXT_NAMESPACE}', 'DEPARTMENT_ID');
                    if l_department is null then
                        return '1=0';
                    end if;
                    return 'department_id = SYS_CONTEXT(''{CONTEXT_NAMESPACE}'', ''DEPARTMENT_ID'')';
                end {PREDICATE_FUNCTION};
                """
            )
            cursor.execute(f"grant execute on {PACKAGE_NAME} to {SESSION_USER}")
            cursor.execute(f"grant select on {TABLE_NAME} to {SESSION_USER}")
        connection.commit()


def _bootstrap_policy(config: OracleSmokeConfig) -> None:
    with _connect(config.admin_user, config.admin_password, config.dsn) as connection:
        with connection.cursor() as cursor:
            _admin_execute(cursor, f"create context {CONTEXT_NAMESPACE} using {OWNER_USER}.{PACKAGE_NAME}")
        connection.commit()

    with _connect(OWNER_USER, OWNER_PASSWORD, config.dsn) as connection:
        with connection.cursor() as cursor:
            cursor.execute(
                f"""
                begin
                    dbms_rls.add_policy(
                        object_schema   => '{OWNER_USER}',
                        object_name     => '{TABLE_NAME}',
                        policy_name     => '{POLICY_NAME}',
                        function_schema => '{OWNER_USER}',
                        policy_function => '{PREDICATE_FUNCTION}',
                        statement_types => 'SELECT'
                    );
                end;
                """
            )
        connection.commit()


@pytest.fixture(scope="module")
def oracle_config() -> OracleSmokeConfig:
    return OracleSmokeConfig()


@pytest.fixture(scope="module")
def prepared_database(oracle_config: OracleSmokeConfig) -> Iterator[OracleSmokeConfig]:
    with _connect(oracle_config.admin_user, oracle_config.admin_password, oracle_config.dsn) as connection:
        _cleanup_security_objects(connection)
        _bootstrap_users(connection)
    try:
        _bootstrap_owner_objects(oracle_config)
        _bootstrap_policy(oracle_config)
        yield oracle_config
    finally:
        try:
            with _connect(oracle_config.admin_user, oracle_config.admin_password, oracle_config.dsn) as connection:
                _cleanup_security_objects(connection)
        except Exception as exc:
            warnings.warn(f"Oracle VPD teardown cleanup failed: {exc}", stacklevel=2)


@pytest.fixture()
def vpd_client(prepared_database: OracleSmokeConfig) -> Iterator[OracleVPDClient]:
    pool = create_proxy_pool(
        OracleVPDPoolConfig(
            dsn=prepared_database.dsn,
            proxy_user=PROXY_USER,
            proxy_password=PROXY_PASSWORD,
            session_user=SESSION_USER,
        )
    )
    client = OracleVPDClient(
        pool,
        context_package_call=f"{OWNER_USER}.{PACKAGE_NAME}.SET_SCOPE",
        clear_context_call=f"{OWNER_USER}.{PACKAGE_NAME}.CLEAR_SCOPE",
    )
    try:
        yield client
    finally:
        client.close()


def test_allowed_scope_returns_only_permitted_rows(vpd_client: OracleVPDClient) -> None:
    rows = vpd_client.fetch_all(
        f"select scope_value from {OWNER_USER}.{TABLE_NAME} order by row_id",
        department_id="sales",
        principal_id=f"user-{uuid4()}",
    )

    assert rows == [("sales-only-row",)]


def test_database_vpd_cannot_be_bypassed_by_application_filter(vpd_client: OracleVPDClient) -> None:
    rows = vpd_client.fetch_all(
        f"select scope_value from {OWNER_USER}.{TABLE_NAME} where department_id = 'finance'",
        department_id="sales",
        principal_id=f"user-{uuid4()}",
    )

    assert rows == []


def test_context_is_cleared_before_connection_reuse(vpd_client: OracleVPDClient) -> None:
    sales_rows = vpd_client.fetch_all(
        f"select scope_value from {OWNER_USER}.{TABLE_NAME} order by row_id",
        department_id="sales",
        principal_id=f"user-{uuid4()}",
    )
    cleared_value = vpd_client.fetch_scalar(f"select sys_context('{CONTEXT_NAMESPACE}', 'DEPARTMENT_ID') from dual")
    finance_rows = vpd_client.fetch_all(
        f"select scope_value from {OWNER_USER}.{TABLE_NAME} order by row_id",
        department_id="finance",
        principal_id=f"user-{uuid4()}",
    )

    assert sales_rows == [("sales-only-row",)]
    assert cleared_value is None
    assert finance_rows == [("finance-only-row",)]
