/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by @tanstack/router-vite-plugin.
// Do not edit this file manually — run `npm run dev` or `npm run build` to regenerate.

import { createFileRoute, createRootRoute } from '@tanstack/react-router'

// Route tree stub for Story 1.7 — routes are discovered at dev/build time
// The Vite plugin will regenerate this file with actual route definitions.

import type { FileRouteTypes } from './routeTree.types'

export type { FileRouteTypes }

export interface RootRouteChildren {}

const rootRoute = createRootRoute()

export const routeTree = rootRoute
