// routeTree.types.ts — Type definitions for route tree
// Generated by @tanstack/router-vite-plugin
export interface FileRouteTypes {
  fileRoutesByFullPath: {
    '/': typeof import('./routes/index').Route;
    '/login': typeof import('./routes/login').Route;
    '/auth/callback': typeof import('./routes/auth/callback').Route;
  };
  fullPaths: '/' | '/login' | '/auth/callback';
  fileRoutesByTo: {
    '/': typeof import('./routes/index').Route;
    '/login': typeof import('./routes/login').Route;
    '/auth/callback': typeof import('./routes/auth/callback').Route;
  };
  to: '/' | '/login' | '/auth/callback';
  id: '__root__' | '/' | '/login' | '/auth/callback';
  fileRoutesById: {
    __root__: typeof import('./routes/__root').Route;
    '/': typeof import('./routes/index').Route;
    '/login': typeof import('./routes/login').Route;
    '/auth/callback': typeof import('./routes/auth/callback').Route;
  };
}
